"""Add composite index to bookmarks

Revision ID: 4697870e9cb7
Revises: c654c861fc9b
Create Date: 2025-07-13 22:23:46.617632

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4697870e9cb7"
down_revision: Union[str, Sequence[str], None] = "c654c861fc9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_bookmarks_user_id_created_at",
        "bookmarks",
        ["user_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bookmarks_user_id_created_at", table_name="bookmarks")
    # ### end Alembic commands ###
