"""Add views_count to Bookmark model

Revision ID: c654c861fc9b
Revises: ffbbd843903a
Create Date: 2025-07-13 21:50:30.430422

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c654c861fc9b"
down_revision: Union[str, Sequence[str], None] = "ffbbd843903a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookmarks", sa.Column("views_count", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookmarks", "views_count")
    # ### end Alembic commands ###
