"""Add AI fields to Bookmark model

Revision ID: f7e94769933a
Revises: 4697870e9cb7
Create Date: 2025-08-01 14:12:03.162792

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "f7e94769933a"
down_revision: Union[str, Sequence[str], None] = "4697870e9cb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
