"""Initial tables

Revision ID: ffbbd843903a
Revises:
Create Date: 2025-07-13 15:05:08.552417

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ffbbd843903a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
